version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: cs-api
    restart: unless-stopped
    ports:
      - "5000:5000"
    environment:
      - NODE_ENV=production
      - MONGODB=mongodb://mongo:27017/cs-api
      - PORT=5000
    networks:
      - cs-network
    depends_on:
      - mongo

  mongo:
    image: mongo:6.0-alpine
    container_name: cs-mongodb
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    networks:
      - cs-network
    command: mongod --quiet --logpath /dev/null # Reduces log output

networks:
  cs-network:
    driver: bridge

volumes:
  mongo-data:
    driver: local
